### ISSUE TITLE
Observation shape issue

### ISSUE THREAD

**Issue by anthonyivol** [iamlucaswolf/gym-chess#4]
HI,

I am trying to make a wrapper around gym-chess for this repo : https://github.com/werner-duvaud/muzero-general
The wrapper here : https://github.com/anthonyivol/muzero-general/blob/master/games/chess.py
And a colab here : https://colab.research.google.com/drive/1fr26XpcZbnv9XQSc4NTIUT3P0k5kjTto?usp=sharing

However I got an error related to the observation shape at init :
`Observation should be 3 dimensionnal instead of 5 dimensionnal. Got observation of shape: (1, 1, 8, 8, 119)`

Any idea on why I got an observation shape of 5 dimensions ? 
Is it because this env use a Box for observation, if so then possible to use only a numpy array  ?

Also the config accept an observation_space of shape (channel, width, height) so I suppose ( 119, 8, 8) for this env but  it looks like that observation shape of gym-chess is (width, height, channel).

How to revert the shape order **properly** to get the channel first ? I guess I can use `observation = moveaxis(observation, 2, 0)`

Thanks for your advice

**Comment by iamlucaswolf** [comment]
Hi @anthonyivol ,

I just had a brief look at your code, but here's what I gathered:

Regarding the **extra dimensions**: You seem to add those yourself in the return statements of `step` (l. 135) and `reset` (l. 166). In general `[x]` in Python will create a new list containing `x`, therefore `[[self.env.reset()]]` will create two nested lists with the inner one containing the return value of `self.env.reset()`. Converting the entire expression into a NumPy array then adds the two leading dimensions. Is there a reason for doing this? Simply returning `self.env.reset()` should be sufficient here..

Regarding the **shape order**:  `np.moveaxis(observation, 2, 0)` should work, as does `np.moveaxis(observation, -1, 0)` or `np.transpose(observation, [1, 2, 0])`. I would probably prefer the latter, but it's really just a matter of taste.

Let me know if that helped, good luck with your project! :)

**Comment by anthonyivol** [comment]
Thanks !
